version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SITE_STATS_API_HOST: http://localhost:8000
    environment:
      - REACT_APP_SITE_STATS_API_HOST=http://localhost:8000
      - VITE_SITE_STATS_API_HOST=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/dist:/copy/dist
    command: npm run dev
  
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    ports:
      - "5434:5432"  # Maps laptop:container (so your host can still access if needed)
    environment:
      POSTGRES_DB: site-stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgres:5432/site-stats}
      - ENV=production
volumes:
  postgres_data:
    
