version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SITE_STATS_API_HOST: http://backend:8000
    environment:
      - REACT_APP_SITE_STATS_API_HOST=http://backend:8000
      - VITE_SITE_STATS_API_HOST=http://backend:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/dist:/copy/dist
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env.docker
    
